export const CONTRACTS = {
  MockERC20: 'MockERC20',
  ERC20: '@openzeppelin/contracts/token/ERC20/ERC20.sol:ERC20',
  MockErc721: 'MockErc721',
  MockErc1155: 'MockErc1155',
  MockErc721Dex: 'MockErc721Dex',
  MockErc20Dex: 'MockErc20Dex',
  MockErc1155Dex: 'MockErc1155Dex',
  WNATIVE: 'WNATIVE',
  Permit2: 'Permit2',
  DZapZapCore: 'DZapZapCore',
  DZapWallet: 'DZapWallet',
  DZapWalletFactory: 'DZapWalletFactory',
  DZapWalletManager: 'DZapWalletManager',
  DZapExecutor: 'DZapExecutor',
  AerodromeClFarmingAdapter: 'AerodromeClFarmingAdapter',
  FluidVaultAdapter: 'FluidVaultAdapter',
  DisperseEthAdapter: 'DisperseEthAdapter',
  MockErc721Staking: 'MockErc721Staking',
}

export const ERRORS = {
  OwnableUnauthorizedAccount: 'OwnableUnauthorizedAccount',
  ZeroAddress: 'ZeroAddress',
  CallerIsNotOwnerOrExecutor: 'CallerIsNotOwnerOrExecutor',
  NoTransferToNullAddress: 'NoTransferToNullAddress',
  IntegratorIsZeroAddress: 'IntegratorIsZeroAddress',
  DustReceiverIsZeroAddress: 'DustReceiverIsZeroAddress',
  ReferralAlreadyAdded: 'ReferralAlreadyAdded',
  InvalidWalletImp: 'InvalidWalletImp',
  AlreadyDeployed: 'AlreadyDeployed',
  AddressIsWallet: 'AddressIsWallet',
  InvalidNativeValue: 'InvalidNativeValue',
  CallFailed: 'CallFailed',
  UnauthorizedSigner: 'UnauthorizedSigner',
  SigDeadlineExpired: 'SigDeadlineExpired',
  NonceAlreadyProcessed: 'NonceAlreadyProcessed',
  ExecutorNotWhitelisted: 'ExecutorNotWhitelisted',
  VerifierNotWhitelisted: 'VerifierNotWhitelisted',
  InvalidInitialization: 'InvalidInitialization',
  EnforcedPause: 'EnforcedPause',
  NoLabel: 'NoLabel',
  ExecutorUnauthorizedAccount: 'ExecutorUnauthorizedAccount',
  QuorumTooLow: 'QuorumTooLow',
  NotAValidator: 'NotAValidator',
  InvalidSignatureLength: 'InvalidSignatureLength',
  SignatureAlreadyProcessed: 'SignatureAlreadyProcessed',
  QuorumNotReached: 'QuorumNotReached',
  WalletNotDeployed: 'WalletNotDeployed',
  WalletExecutionFailed: 'WalletExecutionFailed',
  ZapExecutionFailed: 'ZapExecutionFailed',
  ERC20InsufficientAllowance: 'ERC20InsufficientAllowance',
  InvalidInputLength: 'InvalidInputLength',
  InvalidOutputLength: 'InvalidOutputLength',
  InvalidReturnAmount: 'InvalidReturnAmount',
  InvalidTokenOwner: 'InvalidTokenOwner',
  WalletIsPaused: 'WalletIsPaused',
  UnauthorizedCall: 'UnauthorizedCall',
  ReentrancyGuardReentrantCall: 'ReentrancyGuardReentrantCall',
  SelfCallNotAllowed: 'SelfCallNotAllowed',
  ProtectedSelector: 'ProtectedSelector',

  CallerIsNotOwnerOrAdmin: 'CallerIsNotOwnerOrAdmin',
  InvalidProtocolFeeVault: 'InvalidProtocolFeeVault',
  UniswapPermit2AlreadySet: 'UniswapPermit2AlreadySet',
  UniswapPermit2ByteCodeMismatch: 'UniswapPermit2ByteCodeMismatch',
}

export const EVENTS = {
  ProtocolFeeVaultSet: 'ProtocolFeeVaultSet',
  ZapVerifierSet: 'ZapVerifierSet',
  Permit2Updated: 'Permit2Updated',
  AdminAdded: 'AdminAdded',
  AdminRemoved: 'AdminRemoved',
  AdaptersWhitelistingUpdated: 'AdaptersWhitelistingUpdated',
  TokenRecovered: 'TokenRecovered',
  ERC721Recovered: 'ERC721Recovered',
  ERC1155Recovered: 'ERC1155Recovered',
  Paused: 'Paused',
  Unpaused: 'Unpaused',
  Zapped: 'Zapped',
  GaslessZapped: 'GaslessZapped',
  SelectorsBlacklistingUpdated: 'SelectorsBlacklistingUpdated',

  CallsWhitelistingUpdated: 'CallsWhitelistingUpdated',
  Executed: 'Executed',
  ExecutedWithDeadline: 'ExecutedWithDeadline',
  WalletDeployed: 'WalletDeployed',
  WalletImpUpdated: 'WalletImpUpdated',
  ExecutorWhitelistingUpdated: 'ExecutorWhitelistingUpdated',
  ValidatorWhitelistingUpdated: 'ValidatorWhitelistingUpdated',
  QuorumUpdated: 'QuorumUpdated',
  DeployAndExecuted: 'DeployAndExecuted',
  WalletPaused: 'WalletPaused',
  WalletFactoryUpdated: 'WalletFactoryUpdated',
}

export const FUNCTIONS_NAMES = {
  execute: 'execute',
  deployWalletAndExecute: 'deployWalletAndExecute',
  zap: 'zap(bytes32,bytes,bytes,uint256,address,(address,uint256,bytes)[],(address,(address,uint256,uint256)[]),(address,address,bytes,bool,uint256,(uint8,uint8,address,uint256,uint256)[],(uint8,uint8,address,address,uint96,uint256,uint256)[])[],address[])',
  zapWithBatchPermitDeposit:
    'zap(bytes32,bytes,bytes,bytes,uint256,address,((address,uint256)[],uint256,uint256),(address,(address,uint256,uint256)[]),(address,address,bytes,bool,uint256,(uint8,uint8,address,uint256,uint256)[],(uint8,uint8,address,address,uint96,uint256,uint256)[])[],address[])',
  executeZap:
    'executeZap(bytes32,bytes,bytes,bytes,uint256,uint256,address,address,(address,uint256,bytes)[],(address,(address,uint256,uint256)[]),(address,uint256)[],(address,address,bytes,bool,uint256,(uint8,uint8,address,uint256,uint256)[],(uint8,uint8,address,address,uint96,uint256,uint256)[])[],address[])',
  executeZapWithBatchPermitDeposit:
    'executeZap(bytes32,bytes,bytes,bytes,uint256,address,address,((address,uint256)[],uint256,uint256),(address,(address,uint256,uint256)[]),(address,uint256)[],(address,address,bytes,bool,uint256,(uint8,uint8,address,uint256,uint256)[],(uint8,uint8,address,address,uint96,uint256,uint256)[])[],address[])',
} as const

export const CONTRACTS_PATH = {
  DZapZapCore: 'contracts/zap/DZapZapCore.sol:DZapZapCore',
  DZapWallet: 'contracts/wallet/DZapWallet.sol:DZapWallet',
  DZapWalletFactory: 'contracts/wallet/DZapWalletFactory.sol:DZapWalletFactory',
  DZapWalletManager: 'contracts/wallet/DZapWalletManager.sol:DZapWalletManager',
  DZapExecutor: 'contracts/wallet/DZapExecutor.sol:DZapExecutor',
  AerodromeClFarmingAdapter:
    'contracts/adapters/aerodrome/AerodromeClFarmingAdapter.sol:AerodromeClFarmingAdapter',
  FluidVaultAdapter:
    'contracts/adapters/fluid/FluidVaultAdapter.sol:FluidVaultAdapter',
  DisperseEthAdapter:
    'contracts/adapters/others/DisperseEthAdapter.sol:DisperseEthAdapter',
}
