export const CONTRACTS = {
  MockERC20: 'MockERC20',
  ERC20: '@openzeppelin/contracts/token/ERC20/ERC20.sol:ERC20',
  MockErc721: 'MockErc721',
  MockErc1155: 'MockErc1155',
  MockErc721Dex: 'MockErc721Dex',
  MockErc20Dex: 'MockErc20Dex',
  MockErc1155Dex: 'MockErc1155Dex',
  WNATIVE: 'WNATIVE',
  Permit2: 'Permit2',
  DZapZapCore: 'DZapZapCore',
  DZapWallet: 'DZapWallet',
  DZapWalletFactory: 'DZapWalletFactory',
  DZapRegistry: 'DZapRegistry',
  DZapExecutor: 'DZapExecutor',
  AerodromeClFarmingAdapter: 'AerodromeClFarmingAdapter',
  FluidVaultAdapter: 'FluidVaultAdapter',
  DisperseEthAdapter: 'DisperseEthAdapter',
  MockErc721Staking: 'MockErc721Staking',
}

export const ERRORS = {
  OwnableUnauthorizedAccount: 'OwnableUnauthorizedAccount',
  InvalidFeeVault: 'InvalidFeeVault',
  ZeroAddress: 'ZeroAddress',
  UnauthorizedCaller: 'UnauthorizedCaller',
  NoTransferToNullAddress: 'NoTransferToNullAddress',
  ReferralAlreadyAdded: 'ReferralAlreadyAdded',
  InvalidWalletImp: 'InvalidWalletImp',
  AlreadyDeployed: 'AlreadyDeployed',
  AddressIsWallet: 'AddressIsWallet',
  InvalidNativeValue: 'InvalidNativeValue',
  CallFailed: 'CallFailed',
  UnauthorizedSigner: 'UnauthorizedSigner',
  SigDeadlineExpired: 'SigDeadlineExpired',
  NonceAlreadyProcessed: 'NonceAlreadyProcessed',
  ExecutorNotWhitelisted: 'ExecutorNotWhitelisted',
  VerifierNotWhitelisted: 'VerifierNotWhitelisted',
  InvalidInitialization: 'InvalidInitialization',
  EnforcedPause: 'EnforcedPause',
  NoLabel: 'NoLabel',
  ExecutorUnauthorizedAccount: 'ExecutorUnauthorizedAccount',
  QuorumTooLow: 'QuorumTooLow',
  NotAValidator: 'NotAValidator',
  InvalidSignatureLength: 'InvalidSignatureLength',
  SignatureAlreadyProcessed: 'SignatureAlreadyProcessed',
  QuorumNotReached: 'QuorumNotReached',
  WalletNotDeployed: 'WalletNotDeployed',
  WalletExecutionCallFailed: 'WalletExecutionCallFailed',
  ERC20InsufficientAllowance: 'ERC20InsufficientAllowance',
  InvalidInputLength: 'InvalidInputLength',
  InvalidOutputLength: 'InvalidOutputLength',
  InvalidReturnAmount: 'InvalidReturnAmount',
  InvalidTokenOwner: 'InvalidTokenOwner',
}

export const EVENTS = {
  FeeVaultSet: 'FeeVaultSet',
  ZapVerifierSet: 'ZapVerifierSet',
  AdminAdded: 'AdminAdded',
  AdminRemoved: 'AdminRemoved',
  ReferralAdded: 'ReferralAdded',
  TokenRecovered: 'TokenRecovered',
  ERC721Recovered: 'ERC721Recovered',
  ERC1155Recovered: 'ERC1155Recovered',
  DefaultReferralFeeSet: 'DefaultReferralFeeSet',
  Executed: 'Executed',
  ExecutedWithDeadline: 'ExecutedWithDeadline',
  WalletDeployed: 'WalletDeployed',
  WalletImpUpdated: 'WalletImpUpdated',
  ExecutorWhitelistingUpdated: 'ExecutorWhitelistingUpdated',
  ValidatorWhitelistingUpdated: 'ValidatorWhitelistingUpdated',
  Paused: 'Paused',
  Unpaused: 'Unpaused',
  QuorumUpdated: 'QuorumUpdated',
  DeployAndExecuted: 'DeployAndExecuted',
  Zapped: 'Zapped',
}

export enum FUNCTIONS {
  executeByExecutor = 'executeByExecutor',
  execute = 'execute',
  deployWalletAndExecute = 'deployWalletAndExecute',
}
