import { ApiType, Networks } from '../types'

export enum RPC_TYPE {
  ALCHEMY,
  INFURA,
  BLAST_API,
  OTHER,
}

export enum CHAIN_IDS {
  ARBITRUM_MAINNET = 42161,
  ARBITRUM_NOVA = 42170,
  AURORA_MAINNET = 1313161554,
  AURORA_TESTNET = 1313161555,
  AVALANCHE_MAINNET = 43114,
  AVALANCHE_TESTNET = 43113,
  ARTHERA = 10242,
  ABSTRACT_MAINNET = 2741,
  ABSTRACT_TESTNET = 11124,
  BAHAMUT_MAINNET = 5165,
  BASE_MAINNET = 8453,
  BEVM_MAINNET = 11501,
  BITLAYER_MAINNET = 200901,
  BLAST_MAINNET = 81457,
  BOB_MAINNET = 60808,
  BOBA_AVALANCHE = 43288,
  BOBA_BNB = 56288,
  BOBA_ETH = 288,
  BOBA_RINKEBY = 28,
  BSC_MAINNET = 56,
  BSC_TESTNET = 97,
  BTC_MAINNET = 3652501241,
  BTC_MUTINY = 2782866891,
  BTC_TESTNET4 = 675223068,
  BERA_CHAIN_MAINNET = 80094,
  CELO_MAINNET = 42220,
  CONFLUX_E_SPACE_MAINNET = 1030,
  CONFLUX_E_SPACE_TESTNET = 71,
  CORE_MAINNET = 1116,
  CRONOS_MAINNET = 25,
  DOGECHAIN_MAINNET = 2000,
  ETH_KOVAN = 42,
  ETH_MAINNET = 1,
  ETH_RINKEBY = 4,
  FRAXTAL = 252,
  FUSE = 122,
  FANTOM_MAINNET = 250,
  FILECOIN_MAINNET = 314,
  FIRE_MAINNET = 995,
  GANACHE = 1337,
  GNOSIS_MAINNET = 100,
  GRAVITY = 1625,
  HARDHAT = 31337,
  HOLESKY_TESTNET = 17000,
  HECO_MAINNET = 128,
  HECO_TESTNET = 256,
  KAVA_MAINNET = 2222,
  KROMA = 255,
  KYOTO_MAINNET = 1997,
  LINEA_MAINNET = 59144,
  LINEA_TESTNET = 59140,
  LISK_MAINNET = 1135,
  MANTA_MAINNET = 169,
  MANTLE_MAINNET = 5000,
  MANTLE_TESTNET = 5001,
  MERLIN_MAINNET = 4200,
  METIS_MAINNET = 1088,
  MILKOMEDA_DEVNET = 200101,
  MILKOMEDA_MAINNET = 2001,
  MODE_MAINNET = 34443,
  MINT = 185,
  MORPH = 2818,
  MOONBEAM_MAINNET = 1284,
  MOONRIVER = 1285,
  OASIS_SAPPHIRE_MAINNET = 23294,
  OKEX_TESTNET = 65,
  OKX_MAINNET = 66,
  OKX_X1_TESTNET = 195,
  OPBNB_MAINNET = 204,
  OPTIMISM_MAINNET = 10,
  ONTOLOGY = 58,
  POLYGON_MAINNET = 137,
  POLYGON_MUMBAI = 80001,
  POLYGON_ZK = 1101,
  POLYGON_ZK_EVM_MAINNET = 1101,
  POLYGON_ZK_EVM_TESTNET = 1442,
  ROOLUX_MAINNET = 570,
  ROOTSTOCK_MAINNET = 30,
  SAAKURU_MAINNET = 7225878,
  SCROLL_MAINNET = 534352,
  SCROLL_SEPOLIA = 534351,
  SEI_EVM_MAINNET = 1329,
  SEPOLIA_TESTNET = 11155111,
  SHARDEUM_TESTNET_2 = 8081,
  TAIKO_MAINNET = 167000,
  TELOS_MAINNET = 40,
  TELOS_TESTNET = 41,
  TON_MAINNET = 8888888,
  TRON_MAINNET = 728126428,
  TRON_TESTNET = 2494104990,
  VELAS = 106,
  X_LAYER_MAINNET = 196,
  X_LAYER_TESTNET = 195,
  ZETACHAIN_ATHENS_2 = 7001,
  ZETACHAIN_MAINNET = 7000,
  ZKLINK_MAINNET = 810180,
  ZKSYNC_MAINNET = 324,
  ZKSYNC_SEPOLIA_TESTNET = 300,
  ZKFAIR = 42766,
}

export const NETWORKS: Networks = {
  [CHAIN_IDS.GANACHE]: {
    chainId: CHAIN_IDS.GANACHE,
    chainName: 'Ganache',
    shortName: 'ganache',
    rpcUrl: [''],
    explorerUrl: '',
    apiUrl: '',
    apiType: ApiType.OTHER,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.HARDHAT]: {
    chainId: CHAIN_IDS.HARDHAT,
    chainName: 'Hardhat',
    shortName: 'hardhat',
    rpcUrl: [''],
    explorerUrl: '',
    apiUrl: '',
    apiType: ApiType.OTHER,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ETH_MAINNET]: {
    chainId: CHAIN_IDS.ETH_MAINNET,
    chainName: 'Ethereum Mainnet',
    shortName: 'ethereum',
    rpcUrl: ['https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}'],
    explorerUrl: 'https://etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.SEPOLIA_TESTNET]: {
    chainId: CHAIN_IDS.SEPOLIA_TESTNET,
    chainName: 'Sepolia Testnet',
    shortName: 'sepolia',
    rpcUrl: ['https://1rpc.io/sepolia', 'https://rpc.sepolia.org'],
    explorerUrl: 'https://sepolia.etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=11155111',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.HOLESKY_TESTNET]: {
    chainId: CHAIN_IDS.HOLESKY_TESTNET,
    chainName: 'Holesky Testnet',
    shortName: 'holesky',
    rpcUrl: ['https://1rpc.io/holesky'],
    explorerUrl: 'https://holesky.etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=17000',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ARBITRUM_MAINNET]: {
    chainId: CHAIN_IDS.ARBITRUM_MAINNET,
    chainName: 'Arbitrum One',
    shortName: 'arbitrumOne',
    rpcUrl: [
      'https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}',
      'https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}',
      'https://arb1.arbitrum.io/rpc',
      'https://arbitrum-one-rpc.publicnode.com',
    ],
    explorerUrl: 'https://arbiscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=42161',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.OPTIMISM_MAINNET]: {
    chainId: CHAIN_IDS.OPTIMISM_MAINNET,
    shortName: 'optimism',
    chainName: 'Optimism Mainnet',
    rpcUrl: ['https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}'],
    explorerUrl: 'https://optimistic.etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=10',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ZKSYNC_MAINNET]: {
    chainId: CHAIN_IDS.ZKSYNC_MAINNET,
    chainName: 'ZkSync Era',
    shortName: 'zkSync',
    rpcUrl: ['https://mainnet.era.zksync.io', 'https://zksync.drpc.org'],
    explorerUrl: 'https://explorer.zksync.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=324',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ZKSYNC_SEPOLIA_TESTNET]: {
    chainId: CHAIN_IDS.ZKSYNC_SEPOLIA_TESTNET,
    chainName: 'ZkSync Sepolia Mainnet',
    shortName: 'zkSyncSepolia',
    rpcUrl: ['https://sepolia.era.zksync.dev'],
    explorerUrl: 'https://sepolia-era.zksync.network',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=300',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.BASE_MAINNET]: {
    chainId: CHAIN_IDS.BASE_MAINNET,
    chainName: 'Base',
    shortName: 'base',
    rpcUrl: [
      'https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}',
      'https://mainnet.base.org/',
    ],
    explorerUrl: 'https://basescan.org',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=8453',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.POLYGON_MAINNET]: {
    chainId: CHAIN_IDS.POLYGON_MAINNET,
    chainName: 'Polygon Mainnet',
    shortName: 'polygon',
    rpcUrl: [
      'https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}',
      'https://polygon-rpc.com/',
      'https://rpc-mainnet.matic.network',
      'https://matic-mainnet.chainstacklabs.com',
      'https://rpc-mainnet.maticvigil.com',
    ],
    explorerUrl: 'https://polygonscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=137',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'POL', symbol: 'POL', decimals: 18 },
  },
  [CHAIN_IDS.BSC_MAINNET]: {
    chainId: CHAIN_IDS.BSC_MAINNET,
    chainName: 'Binance Smart Chain',
    shortName: 'bsc',
    rpcUrl: [
      'https://bsc-dataseed1.bnbchain.org',
      'https://bsc-dataseed2.bnbchain.org',
      'https://bscrpc.com',
    ],
    explorerUrl: 'https://bscscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=56',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'BNB Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.BSC_TESTNET]: {
    chainId: CHAIN_IDS.BSC_TESTNET,
    chainName: 'Binance Smart Chain Testnet',
    shortName: 'bscTestnet',
    rpcUrl: [
      'https://data-seed-prebsc-1-s1.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s1.bnbchain.org:8545',
      'https://bsc-testnet.public.blastapi.io',
    ],
    explorerUrl: 'https://testnet.bscscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=97',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'BNB Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.AVALANCHE_MAINNET]: {
    chainId: CHAIN_IDS.AVALANCHE_MAINNET,
    chainName: 'Avalanche C-Chain',
    shortName: 'avalanche',
    rpcUrl: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com',
    ],
    explorerUrl: 'https://snowscan.xyz',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=43114',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
  },
  [CHAIN_IDS.MANTA_MAINNET]: {
    chainId: CHAIN_IDS.MANTA_MAINNET,
    chainName: 'Manta Pacific',
    shortName: 'manta',
    rpcUrl: [
      'https://pacific-rpc.manta.network/http',
      'https://manta-pacific.drpc.org',
    ],
    explorerUrl: 'https://pacific-explorer.manta.network',
    apiUrl: 'https://pacific-explorer.manta.network/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.SCROLL_MAINNET]: {
    chainId: CHAIN_IDS.SCROLL_MAINNET,
    chainName: 'Scroll Mainnet',
    shortName: 'scroll',
    rpcUrl: ['https://rpc.scroll.io'],
    explorerUrl: 'https://scrollscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=534352',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.LINEA_MAINNET]: {
    chainId: CHAIN_IDS.LINEA_MAINNET,
    chainName: 'Linea Mainnet',
    shortName: 'linea',
    rpcUrl: ['https://linea-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}'],
    explorerUrl: 'https://lineascan.build',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=59144',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MANTLE_MAINNET]: {
    chainId: CHAIN_IDS.MANTLE_MAINNET,
    chainName: 'Mantle Mainnet',
    shortName: 'mantle',
    rpcUrl: [
      'https://mantle-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}',
      'https://rpc.mantle.xyz',
      'https://mantle-mainnet.blastapi.io',
    ],
    explorerUrl: 'https://mantlescan.xyz',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=5000',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Mantle', symbol: 'MNT', decimals: 18 },
  },
  [CHAIN_IDS.TELOS_MAINNET]: {
    chainId: CHAIN_IDS.TELOS_MAINNET,
    chainName: 'Telos Mainnet',
    shortName: 'telos',
    rpcUrl: [
      'https://rpc.ankr.com/telos',
      'https://mainnet.telos.net/evm',
      'https://telos.drpc.org',
    ],
    explorerUrl: 'https://teloscan.io',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: { name: 'Telos', symbol: 'TLOS', decimals: 18 },
  },
  [CHAIN_IDS.CORE_MAINNET]: {
    chainId: CHAIN_IDS.CORE_MAINNET,
    chainName: 'Core',
    shortName: 'core',
    rpcUrl: [
      'https://rpc.coredao.org/',
      'https://rpc-core.icecreamswap.com',
      'https://core.drpc.org',
    ],
    explorerUrl: 'https://scan.coredao.org',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: { name: 'CORE', symbol: 'CORE', decimals: 18 },
  },
  [CHAIN_IDS.ROOTSTOCK_MAINNET]: {
    chainId: CHAIN_IDS.ROOTSTOCK_MAINNET,
    chainName: 'Rootstock Mainnet',
    shortName: 'rootstock',
    rpcUrl: [
      'https://rootstock-mainnet.blastapi.io',
      'https://public-node.rsk.co',
      'https://mycrypto.rsk.co',
    ],
    explorerUrl: 'https://rootstock.blockscout.com',
    apiUrl: 'https://rootstock.blockscout.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Smart Bitcoin',
      symbol: 'RBTC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.X_LAYER_MAINNET]: {
    chainId: CHAIN_IDS.X_LAYER_MAINNET,
    chainName: 'X-Layer Mainnet',
    shortName: 'xlayer',
    rpcUrl: ['https://xlayerrpc.okx.com', 'https://rpc.xlayer.tech'],
    explorerUrl: 'https://www.oklink.com/xlayer',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: {
      name: 'X Layer Global Utility Token',
      symbol: 'OKB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.POLYGON_ZK_EVM_MAINNET]: {
    chainId: CHAIN_IDS.POLYGON_ZK_EVM_MAINNET,
    chainName: 'Polygon zkEVM Mainnet',
    shortName: 'polygonZk',
    rpcUrl: ['https://zkevm-rpc.com', 'https://polygon-zkevm.drpc.org'],
    explorerUrl: 'https://zkevm.polygonscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1101',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MODE_MAINNET]: {
    chainId: CHAIN_IDS.MODE_MAINNET,
    chainName: 'Mode Mainnet',
    shortName: 'mode',
    rpcUrl: ['https://mainnet.mode.network', 'https://mode.drpc.org'],
    explorerUrl: 'https://explorer.mode.network',
    apiUrl: 'https://explorer.mode.network/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.METIS_MAINNET]: {
    chainId: CHAIN_IDS.METIS_MAINNET,
    chainName: 'Metis Andromeda',
    shortName: 'metis',
    rpcUrl: ['https://andromeda.metis.io/', 'https://metis.drpc.org'],
    explorerUrl: 'https://andromeda-explorer.metis.io/',
    apiUrl: 'https://andromeda-explorer.metis.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Metis', symbol: 'METIS', decimals: 18 },
  },
  [CHAIN_IDS.CELO_MAINNET]: {
    chainId: CHAIN_IDS.CELO_MAINNET,
    chainName: 'Celo',
    shortName: 'celo',
    rpcUrl: ['https://forno.celo.org'],
    explorerUrl: 'https://celoscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=42220',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'CELO', symbol: 'CELO', decimals: 18 },
  },
  [CHAIN_IDS.ZETACHAIN_MAINNET]: {
    chainId: CHAIN_IDS.ZETACHAIN_MAINNET,
    chainName: 'Zetachain Mainnet',
    shortName: 'zeta',
    rpcUrl: [
      'https://zetachain-mainnet.public.blastapi.io',
      'https://zetachain-evm.blockpi.network/v1/rpc/public',
    ],
    explorerUrl: 'https://zetachain.blockscout.com',
    apiUrl: 'https://zetachain.blockscout.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Zeta', symbol: 'ZETA', decimals: 18 },
  },
  [CHAIN_IDS.BLAST_MAINNET]: {
    chainId: CHAIN_IDS.BLAST_MAINNET,
    chainName: 'Blast',
    shortName: 'blast',
    rpcUrl: ['https://rpc.blast.io', 'https://rpc.ankr.com/blast'],
    explorerUrl: 'https://blastscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=81457',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.BOBA_ETH]: {
    chainId: CHAIN_IDS.BOBA_ETH,
    chainName: 'Boba ETH',
    shortName: 'bobaEth',
    rpcUrl: ['https://mainnet.boba.network'],
    explorerUrl: 'https://bobascan.com',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.FRAXTAL]: {
    chainId: CHAIN_IDS.FRAXTAL,
    chainName: 'Fraxtal',
    shortName: 'fraxtal',
    rpcUrl: ['https://rpc.frax.com'],
    explorerUrl: 'https://fraxscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=252',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'Frax Ether',
      symbol: 'frxETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.GRAVITY]: {
    chainId: CHAIN_IDS.GRAVITY,
    chainName: 'Gravity',
    shortName: 'gravity',
    rpcUrl: ['https://rpc.gravity.xyz', 'https://rpc.ankr.com/gravity'],
    explorerUrl: 'https://explorer.gravity.xyz',
    apiUrl: 'https://explorer.gravity.xyz/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Gravity', symbol: 'G', decimals: 18 },
  },
  [CHAIN_IDS.GNOSIS_MAINNET]: {
    chainId: CHAIN_IDS.GNOSIS_MAINNET,
    chainName: 'Gnosis Mainnet',
    shortName: 'gnosis',
    rpcUrl: ['https://gnosis-rpc.publicnode.com'],
    explorerUrl: 'https://gnosisscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=100',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'xDAI', symbol: 'XDAI', decimals: 18 },
  },
  [CHAIN_IDS.FUSE]: {
    chainId: CHAIN_IDS.FUSE,
    chainName: 'Fuse',
    shortName: 'fuse',
    rpcUrl: ['https://rpc.fuse.io'],
    explorerUrl: 'https://explorer.fuse.io',
    apiUrl: 'https://explorer.fuse.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.FANTOM_MAINNET]: {
    chainId: CHAIN_IDS.FANTOM_MAINNET,
    chainName: 'Fantom Mainnet',
    shortName: 'fantom',
    rpcUrl: [
      'https://rpc.ftm.tools',
      'https://fantom-rpc.publicnode.com',
      'https://fantom.drpc.org',
      'https://rpcapi.fantom.network',
      'https://rpc.ankr.com/fantom',
    ],
    explorerUrl: 'https://ftmscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=250',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
  },
  [CHAIN_IDS.MOONBEAM_MAINNET]: {
    chainId: CHAIN_IDS.MOONBEAM_MAINNET,
    chainName: 'Moonbeam Mainnet',
    shortName: 'moonbeam',
    rpcUrl: ['https://moonbeam.public.blastapi.io'],
    explorerUrl: 'https://moonbeam.moonscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1284',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Glimmer', symbol: 'GLMR', decimals: 18 },
  },
  [CHAIN_IDS.MOONRIVER]: {
    chainId: CHAIN_IDS.MOONRIVER,
    chainName: 'MoonRiver',
    shortName: 'moonriver',
    rpcUrl: ['https://moonriver.public.blastapi.io'],
    explorerUrl: 'https://moonriver.moonscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1285',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Moonriver', symbol: 'MOVR', decimals: 18 },
  },
  [CHAIN_IDS.CRONOS_MAINNET]: {
    chainId: CHAIN_IDS.CRONOS_MAINNET,
    chainName: 'Cronos Mainnet',
    shortName: 'cronos',
    rpcUrl: ['https://cronos-evm-rpc.publicnode.com'],
    explorerUrl: 'https://cronoscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=25',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18 },
  },
  [CHAIN_IDS.KAVA_MAINNET]: {
    chainId: CHAIN_IDS.KAVA_MAINNET,
    chainName: 'Kava Mainnet',
    shortName: 'kava',
    rpcUrl: ['https://rpc.ankr.com/kava_evm'],
    explorerUrl: 'https://testnet.kavascan.com',
    apiUrl: 'https://testnet.kavascan.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Kava', symbol: 'KAVA', decimals: 18 },
  },
  [CHAIN_IDS.KROMA]: {
    chainId: CHAIN_IDS.KROMA,
    chainName: 'Kroma',
    shortName: 'kroma',
    rpcUrl: ['https://1rpc.io/kroma'],
    explorerUrl: 'https://kromascan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=255',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.AURORA_MAINNET]: {
    chainId: CHAIN_IDS.AURORA_MAINNET,
    chainName: 'Aurora Mainnet',
    shortName: 'aurora',
    rpcUrl: ['https://mainnet.aurora.dev', 'https://aurora.drpc.org'],
    explorerUrl: 'https://explorer.mainnet.aurora.dev',
    apiUrl: 'https://explorer.mainnet.aurora.dev/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MINT]: {
    chainId: CHAIN_IDS.MINT,
    chainName: 'Mint Mainnet',
    shortName: 'mint',
    rpcUrl: [
      'https://rpc.mintchain.io',
      'https://global.rpc.mintchain.io',
      'https://asia.rpc.mintchain.io',
    ],
    explorerUrl: 'https://explorer.mintchain.io',
    apiUrl: 'https://explorer.mintchain.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ARTHERA]: {
    chainId: CHAIN_IDS.ARTHERA,
    chainName: 'Arthera',
    shortName: 'arthera',
    rpcUrl: ['https://rpc.arthera.net'],
    explorerUrl: 'https://explorer-test.arthera.net',
    apiUrl: 'https://explorer-test.arthera.net/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.TAIKO_MAINNET]: {
    chainId: CHAIN_IDS.TAIKO_MAINNET,
    chainName: 'Taiko Mainnet',
    shortName: 'taiko',
    rpcUrl: [
      'https://rpc.mainnet.taiko.xyz',
      'https://taiko-rpc.publicnode.com',
    ],
    explorerUrl: 'https://taikoscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=167000',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.FIRE_MAINNET]: {
    chainId: CHAIN_IDS.FIRE_MAINNET,
    chainName: '5ire Mainnet',
    shortName: '5ire',
    rpcUrl: ['https://rpc.5ire.network'],
    explorerUrl: 'https://5irescan.io',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: {
      name: '5ire Token',
      symbol: '5ire',
      decimals: 18,
    },
  },
  [CHAIN_IDS.MORPH]: {
    chainId: CHAIN_IDS.MINT,
    chainName: 'Morph Mainnet',
    shortName: 'morph',
    rpcUrl: ['https://rpc-quicknode.morphl2.io'],
    explorerUrl: 'https://explorer.morphl2.io',
    apiUrl: 'https://explorer.morphl2.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MERLIN_MAINNET]: {
    chainId: CHAIN_IDS.MERLIN_MAINNET,
    chainName: 'Merlin Mainnet',
    shortName: 'merlin',
    rpcUrl: ['https://rpc.merlinchain.io'],
    explorerUrl: 'https://scan.merlinchain.io',
    apiUrl: 'https://scan.merlinchain.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'BTC', symbol: 'BTC', decimals: 18 },
  },
  [CHAIN_IDS.BERA_CHAIN_MAINNET]: {
    chainId: CHAIN_IDS.BERA_CHAIN_MAINNET,
    chainName: 'Bera Chain',
    shortName: 'bera',
    rpcUrl: [
      'https://berachain.blockpi.network/v1/rpc/public',
      'https://bartio.rpc.berachain.com',
      'https://bera-testnet.nodeinfra.com',
    ],
    explorerUrl: 'https://berascan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=80094',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'BERA Token',
      symbol: 'BERA',
      decimals: 18,
    },
  },
  [CHAIN_IDS.ABSTRACT_MAINNET]: {
    chainId: CHAIN_IDS.ABSTRACT_MAINNET,
    chainName: 'Abstract',
    shortName: 'abstract',
    rpcUrl: ['https://api.mainnet.abs.xyz', 'https://abstract.drpc.org'],
    explorerUrl: 'https://abscan.org/',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=2741',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.ABSTRACT_TESTNET]: {
    chainId: CHAIN_IDS.ABSTRACT_TESTNET,
    chainName: 'Abstract Testnet',
    shortName: 'abstractTestnet',
    rpcUrl: ['https://api.testnet.abs.xyz'],
    explorerUrl: 'https://sepolia.abscan.org/',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=11124',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
}
